### ISSUE TITLE
Leaking when activity/fragment destory

### ISSUE THREAD

**Issue by ShineYang** [liyuzheng/SimpleMarqueeView#1]
I use LeakCanary and it shows fragment leak with SimpleMarqueeView$startAnim, I checked code find that UpdateListeners was not removed. 
``` kotlin
    private fun stopAnim() {
        anim?.cancel()
        anim?.removeAllListeners()
        //remove update listener
        anim?.removeAllUpdateListeners()
        anim = null
        animValue = 0
    }
```
I tried to remove updateListener and it worked.

**Comment by liyuzheng** [comment]
> I use LeakCanary and it shows fragment leak with SimpleMarqueeView$startAnim, I checked code find that UpdateListeners was not removed.
> 
> ```kotlin
>     private fun stopAnim() {
>         anim?.cancel()
>         anim?.removeAllListeners()
>         //remove update listener
>         anim?.removeAllUpdateListeners()
>         anim = null
>         animValue = 0
>     }
> ```
> 
> I tried to remove updateListener and it worked.

Thanks,I've updated it.
Please use v1.2.0
